apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - command:
        - /manager
        args:
        image: controller:latest
        imagePullPolicy: IfNotPresent
        name: manager
        securityContext:
          privileged: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
          - mountPath: /etc
            name: systemd-config
          - mountPath: /lib/systemd
            name: systemd-lib
          - mountPath: /etc/systemd
            name: systemd-etc
          - mountPath: /run/systemd
            name: systemd-run
      volumes:
        - hostPath:
            path: /etc
            type: Directory
          name: systemd-config
        - hostPath:
            path: /lib/systemd
            type: Directory
          name: systemd-lib
        - hostPath:
            path: /etc/systemd
            type: Directory
          name: systemd-etc
        - hostPath:
            path: /run/systemd
            type: Directory
          name: systemd-run
